### ISSUE TITLE
How to serialise a user-defined type?

### ISSUE THREAD

**Issue by lindig** [inhabitedtype/faraday#1]
Could you expand the README to explain the scope of the serialiser? Looking at the interface it is not obvious how to serialise user-defined types. Maybe this is not even a design goal. In any case, I think the README could address this.

**Comment by seliopou** [comment]
This will definitely be included before Faraday's initial release. It'd be helpful to know what, if any, problems you were trying to solve when you came across the library, and your expectations as to how the library would fit into your solution. For example, it's unclear to me if your expectation was that Faraday would offer a serialization format, or that it would just offer a data structure that would allow you to target a serialization format efficiently. Knowing these sorts of things would be a tremendous help while writing documentation, as it would help me refine the mental model of the user I'm targeting. Thanks!

**Comment by seliopou** [comment]
Usually serialization refers to converting an in-memory object into a representation that's suitable for storage or transmission. In other words, the writing part. For the reading part, [angstrom](https://github.com/inhabitedtype/angstrom) is a library that's well-suited to that use case.

I'm still not clear on what your expectation was. Is it that Faraday would prescribe a particular serialization format for user-defined data types? Honest question.

**Comment by lindig** [comment]
A parser takes a byte stream and creates a data structure representing the abstract objects represented by that byte stream. I expect a serialiser to do the opposite. Say, I have a record representing time and date, I would expect support from a serialisation library to create a byte stream from it. Look at any JSON library: it provides a way to map data structures to JSON syntax. My expectation is that Faraday does something similar, but more efficient. 

I fear we are talking past each other. So maybe you could suggest a scenario where I would want to use Faraday.

**Comment by seliopou** [comment]
Not at all, this back and forth has been helpful and will inform how I document Faraday.

To answer your question directly, you would use Faraday to _write_ the JSON serializer, or the serializer the record that contains a time and a date, or whatever complex, user-defined type that an application is dealing with. So a user of Faraday needs to bring with him a data type to serialize, together with a serialization format, and then use the library to implement the serializer for the data type that targets the serialization format. (Functionality like that contained in the [Marshal](https://caml.inria.fr/pub/docs/manual-ocaml/libref/Marshal.html) module, for example, is not a goal of the library.) A user can use the `write_*` calls to perform copies into an internal buffer, or `schedule_*` calls to add buffers directly to the output without performing a copy. In the case of a `schedule_*` call, the buffer should not be modified until `flush` succeeds. In that way, you can control the allocation and copy behavior of your serializer with an output that's suitable for vectorized write operations, e.g., `writev(2)`.

Does that clarify things? If there's a better way to communicate this, then I'd be thankful for the notes.

**Comment by lindig** [comment]
Yes. The way I understand it now, Faraday does provide serialisation of the base types but (so far) not for sum and product types. It would be my own job to map a binary tree value to the primitives provided by Faraday.

**Comment by seliopou** [comment]
I've included a JSON serializer in the `examples` subdirectory of the project, as well as a simpler example of serializing abstract syntax tree of a simple arithmetic expression language in the README. Those, together with an updated description of the library, should hopefully clarify the purpose and uses of faraday.
